[package]
name = "tidy-themes"
version = "0.1.0"
edition = "2024"
authors = ["Pavel Ivanov <mr.pavel.ivanov@gmail.com>"]
license = "MIT"

[dependencies]
voca_rs = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
