tags = ["light"]

[theme.colors]
background = "#f7f7f7"
foreground = "#4a4543"
bright-foreground = "#4a4543"

[theme.colors.palette]
0 = "#090300"
1 = "#db2d20"
2 = "#01a252"
3 = "#caba00"
4 = "#01a0e4"
5 = "#a16a94"
6 = "#8fbece"
7 = "#a5a2a2"
8 = "#5c5855"
9 = "#dbaec3"
10 = "#3a3432"
11 = "#4a4543"
12 = "#807d7c"
13 = "#bcbbba"
14 = "#cdab53"
15 = "#f7f7f7"
