tags = ["light"]

[theme.colors]
background = "#ffffff"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#241f31"
1 = "#c01c28"
2 = "#2ec27e"
3 = "#e8b504"
4 = "#1e78e4"
5 = "#9841bb"
6 = "#0ab9dc"
7 = "#c0bfbc"
8 = "#5e5c64"
9 = "#ed333b"
10 = "#4ad67c"
11 = "#d2be36"
12 = "#51a1ff"
13 = "#c061cb"
14 = "#4fd2fd"
15 = "#f6f5f4"
