tags = ["dark"]

[theme.colors]
background = "#1f2430"
foreground = "#cccac2"
bright-foreground = "#cccac2"

[theme.colors.palette]
0 = "#171b24"
1 = "#ed8274"
2 = "#87d96c"
3 = "#facc6e"
4 = "#6dcbfa"
5 = "#dabafa"
6 = "#90e1c6"
7 = "#c7c7c7"
8 = "#686868"
9 = "#f28779"
10 = "#d5ff80"
11 = "#ffd173"
12 = "#73d0ff"
13 = "#dfbfff"
14 = "#95e6cb"
15 = "#ffffff"
