tags = ["dark"]

[theme.colors]
background = "#0b0e14"
foreground = "#bfbdb6"
bright-foreground = "#bfbdb6"

[theme.colors.palette]
0 = "#11151c"
1 = "#ea6c73"
2 = "#7fd962"
3 = "#f9af4f"
4 = "#53bdfa"
5 = "#cda1fa"
6 = "#90e1c6"
7 = "#c7c7c7"
8 = "#686868"
9 = "#f07178"
10 = "#aad94c"
11 = "#ffb454"
12 = "#59c2ff"
13 = "#d2a6ff"
14 = "#95e6cb"
15 = "#ffffff"
