tags = ["light"]

[theme.colors]
background = "#ffffff"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#000000"
1 = "#bb0000"
2 = "#00bb00"
3 = "#bbbb00"
4 = "#0000bb"
5 = "#bb00bb"
6 = "#00bbbb"
7 = "#bbbbbb"
8 = "#555555"
9 = "#ff5555"
10 = "#2fd92f"
11 = "#bfbf15"
12 = "#5555ff"
13 = "#ff55ff"
14 = "#22cccc"
15 = "#ffffff"
