tags = ["dark"]

[theme.colors]
background = "#232136"
foreground = "#e0def4"
bright-foreground = "#e0def4"

[theme.colors.palette]
0 = "#393552"
1 = "#eb6f92"
2 = "#a3be8c"
3 = "#f6c177"
4 = "#569fba"
5 = "#c4a7e7"
6 = "#9ccfd8"
7 = "#e0def4"
8 = "#544d8a"
9 = "#f083a2"
10 = "#b1d196"
11 = "#f9cb8c"
12 = "#65b1cd"
13 = "#ccb1ed"
14 = "#a6dae3"
15 = "#e2e0f7"
