tags = ["light"]

[theme.colors]
background = "#fdf0ed"
foreground = "#16161d"
bright-foreground = "#16161d"

[theme.colors.palette]
0 = "#16161d"
1 = "#fc4777"
2 = "#00ca86"
3 = "#f2a682"
4 = "#00bedd"
5 = "#ff58b1"
6 = "#00cdcb"
7 = "#bfafac"
8 = "#1a1c24"
9 = "#fe5f87"
10 = "#00d193"
11 = "#e5a688"
12 = "#00c9e2"
13 = "#ff6cba"
14 = "#00c3c2"
15 = "#fff2ef"
