tags = ["dark"]

[theme.colors]
background = "#141414"
foreground = "#cecece"
bright-foreground = "#cecece"

[theme.colors.palette]
0 = "#141414"
1 = "#d03333"
2 = "#1bd01b"
3 = "#d08c1b"
4 = "#1b1bd0"
5 = "#d01bd0"
6 = "#1bd0d0"
7 = "#cecece"
8 = "#4e4e4e"
9 = "#dc4e4e"
10 = "#4edc4e"
11 = "#f3f34e"
12 = "#4e4edc"
13 = "#f34ef3"
14 = "#4ef3f3"
15 = "#ffffff"
