tags = ["dark"]

[theme.colors]
background = "#121212"
foreground = "#bebebe"
bright-foreground = "#bebebe"

[theme.colors.palette]
0 = "#333333"
1 = "#d35f5f"
2 = "#ffc107"
3 = "#b91c1c"
4 = "#e68e0d"
5 = "#d35f5f"
6 = "#bebebe"
7 = "#bebebe"
8 = "#8a8a8d"
9 = "#891c1c"
10 = "#ffc107"
11 = "#b90a0a"
12 = "#f59e0b"
13 = "#b91c1c"
14 = "#eaeaea"
15 = "#ffffff"
