tags = ["dark"]

[theme.colors]
background = "#271f19"
foreground = "#ffffff"
bright-foreground = "#ffffff"

[theme.colors.palette]
0 = "#000000"
1 = "#9a1a1a"
2 = "#61ce3c"
3 = "#fbde2d"
4 = "#324883"
5 = "#ff0080"
6 = "#8da6ce"
7 = "#f8f8f8"
8 = "#4c4c4c"
9 = "#9a1a1a"
10 = "#61ce3c"
11 = "#fbde2d"
12 = "#324883"
13 = "#ff0080"
14 = "#8da6ce"
15 = "#f8f8f8"
