tags = ["dark"]

[theme.colors]
background = "#07273b"
foreground = "#becfda"
bright-foreground = "#becfda"

[theme.colors.palette]
0 = "#28353e"
1 = "#e66533"
2 = "#49e9a6"
3 = "#e4b781"
4 = "#49ace9"
5 = "#df769b"
6 = "#49d6e9"
7 = "#aec3d0"
8 = "#475e6c"
9 = "#e97749"
10 = "#60ebb1"
11 = "#e69533"
12 = "#60b6eb"
13 = "#e798b3"
14 = "#60dbeb"
15 = "#becfda"
