tags = ["light"]

[theme.colors]
background = "#e5e9f0"
foreground = "#414858"
bright-foreground = "#414858"

[theme.colors.palette]
0 = "#3b4252"
1 = "#bf616a"
2 = "#96b17f"
3 = "#c5a565"
4 = "#81a1c1"
5 = "#b48ead"
6 = "#7bb3c3"
7 = "#a5abb6"
8 = "#4c566a"
9 = "#bf616a"
10 = "#96b17f"
11 = "#c5a565"
12 = "#81a1c1"
13 = "#b48ead"
14 = "#82afae"
15 = "#eceff4"
