tags = ["dark"]

[theme.colors]
background = "#2e3440"
foreground = "#cdcecf"
bright-foreground = "#cdcecf"

[theme.colors.palette]
0 = "#3b4252"
1 = "#bf616a"
2 = "#a3be8c"
3 = "#ebcb8b"
4 = "#81a1c1"
5 = "#b48ead"
6 = "#88c0d0"
7 = "#e5e9f0"
8 = "#465780"
9 = "#d06f79"
10 = "#b1d196"
11 = "#f0d399"
12 = "#8cafd2"
13 = "#c895bf"
14 = "#93ccdc"
15 = "#e7ecf4"
