tags = ["dark"]

[theme.colors]
background = "#224fbc"
foreground = "#ffffff"
bright-foreground = "#ffffff"

[theme.colors.palette]
0 = "#000000"
1 = "#e64c4c"
2 = "#00a600"
3 = "#999900"
4 = "#0000b2"
5 = "#d826d8"
6 = "#00a6b2"
7 = "#bfbfbf"
8 = "#808080"
9 = "#ff1a1a"
10 = "#00d900"
11 = "#e5e500"
12 = "#7373ff"
13 = "#e500e5"
14 = "#00e5e5"
15 = "#e5e5e5"
