#:schema https://raw.githubusercontent.com/pamburus/termframe/refs/heads/main/schema/json/theme.schema.json

tags = ["dark", "light"]

[theme.modes.dark.colors]
background = "#282c34"
foreground = "#dcdfe4"
bright-foreground = "#f7f9fc"

[theme.modes.dark.colors.palette]
0 = "#3e4451"
1 = "#e06c75"
2 = "#98c379"
3 = "#e5c07b"
4 = "#61afef"
5 = "#c678dd"
6 = "#56b6c2"
7 = "#dcdfe4"
8 = "#545d6d"
9 = "#fd807f"
10 = "#96d58a"
11 = "#edc273"
12 = "#84c8ff"
13 = "#ee82ee"
14 = "#3ae1f7"
15 = "#f7f9fc"

[theme.modes.light.colors]
background = "#fafafa"
foreground = "#383a42"
bright-foreground = "#0f131e"

[theme.modes.light.colors.palette]
0 = "#464b57"
1 = "#e45649"
2 = "#50a14f"
3 = "#c18401"
4 = "#0184bc"
5 = "#a626a4"
6 = "#0997b3"
7 = "#e8d9d9"
8 = "#0f131e"
9 = "#f24c2d"
10 = "#3db637"
11 = "#e09d00"
12 = "#2e63d6"
13 = "#d21fd1"
14 = "#06b1d8"
15 = "#ffffff"
