tags = ["light"]

[theme.colors]
background = "#f8f8ff"
foreground = "#1d1d26"
bright-foreground = "#1d1d26"

[theme.colors.palette]
0 = "#1d1d26"
1 = "#ff3399"
2 = "#00d364"
3 = "#e5b24d"
4 = "#00cbff"
5 = "#cc66ff"
6 = "#00ceca"
7 = "#b1b1d6"
8 = "#636667"
9 = "#ff2f92"
10 = "#00d364"
11 = "#d9ae53"
12 = "#00cbff"
13 = "#d783ff"
14 = "#00c8c7"
15 = "#d5d6f3"
