tags = ["dark"]

[theme.colors]
background = "#3f3f3f"
foreground = "#dcdccc"
bright-foreground = "#dcdccc"

[theme.colors.palette]
0 = "#4d4d4d"
1 = "#7d5d5d"
2 = "#60b48a"
3 = "#f0dfaf"
4 = "#5d6d7d"
5 = "#dc8cc3"
6 = "#8cd0d3"
7 = "#dcdccc"
8 = "#709080"
9 = "#dca3a3"
10 = "#c3bf9f"
11 = "#e0cf9f"
12 = "#94bff3"
13 = "#ec93d3"
14 = "#93e0e3"
15 = "#ffffff"
