terminal:
  width: 160
  height: 80

font:
  family: "JetBrains Mono"
  size: 12

line-height: 1.2
precision: 3
padding: 4
theme: "one-dark"

fonts:
  - family: "JetBrains Mono"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Regular.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Italic.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Bold.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-BoldItalic.woff2"

  - family: "Spline Sans Mono"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Regular.woff2"
      - "https://fonts.gstatic.com/s/splinesansmono/v10/R70BjzAei_CDNLfgZxrW6wrZOF2WX5KZmE-Z-lw.woff2"
      - "https://fonts.gstatic.com/s/splinesansmono/v10/R70HjzAei_CDNLfgZxrW6wrZOF2WX5epmkWe2F5QuA.woff2"

  - family: "Victor Mono"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Regular.woff2"
      - "https://fonts.gstatic.com/s/victormono/v3/Yq6Q-LGQWyfv-LGy7lEO0_ZdtxUGS7ZG.woff2"
      - "https://fonts.gstatic.com/s/victormono/v3/Yq6S-LGQWyfv-LGy7lEO0_ZYhxcMTJRE49A.woff2"

  - family: "Roboto Mono"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/webfonts/JetBrainsMono-Regular.woff2"
      - "https://fonts.gstatic.com/s/robotomono/v23/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2"
      - "https://fonts.gstatic.com/s/robotomono/v23/L0x7DF4xlVMF-BfR8bXMIjhOm32WWpCBC10.woff2"
