# Terminal settings.
terminal:
  # Terminal width in characters.
  width: 80
  # Terminal width in characters.
  height: 24

# Font settings.
font:
  # Font family.
  family: "JetBrains Mono"
  # Font size in pixels.
  size: 12
  # Font weights per ANSI style.
  weights:
    # Font weight for normal ANSI style.
    normal: normal
    # Font weight for bol ANSI style.
    bold: bold
    # Font weight for faint/dim ANSI style.
    faint: normal

# Embed fonts in the output SVG file.
embed-fonts: false

# Subset fonts to only include the characters used in the output SVG file.
# Experimental feature, has compatibility issues with some browsers.
subset-fonts: false

# Line height in em units, that is relative the font size.
line-height: 1.2

# Floating point precision for rendering.
precision: 3

# Text padding in em units.
padding:
  # Horizontal padding.
  horizontal: 0.8
  # Vertical padding.
  vertical: 0.6

# Color theme.
# For the list of available themes, run `termframe --list-themes`.
theme:
  # Color theme for dark mode.
  dark: "termframe"
  # Color theme for light mode.
  light: "termframe"

# Use bright colors for bold text.
bold-is-bright: false

# Faint/dim text opacity.
faint-opacity: 0.5

# Dark or light mode.
# Possible values: [auto, dark, light].
mode: auto

# Extra stroke over the filled background elements.
# This is needed to avoid rendering artifacts in some browsers.
stroke: 0.01

# Terminal window settings.
window:
  # Enable or disable terminal window in the output SVG file.
  enabled: true
  # Enable or disable shadow for the terminal window.
  shadow: true
  # Terminal window style.
  # For the list of available styles, run `termframe --list-window-styles`.
  style: "macos"

# Font settings.
# For the list of available fonts, run `termframe --list-fonts`.
fonts:
  - family: "JetBrains Mono"
    license:
      type: "SIL Open Font License 1.1"
      link: "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/OFL.txt"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/variable/JetBrainsMono%5Bwght%5D.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/JetBrainsMono/fonts/variable/JetBrainsMono-Italic%5Bwght%5D.woff2"

  - family: "Source Code Pro"
    license:
      type: "SIL Open Font License 1.1"
      link: "https://github.com/adobe-fonts/source-code-pro/blob/2.042R-u/1.062R-i/1.026R-vf/LICENSE.md"
    files:
      - "https://raw.githubusercontent.com/adobe-fonts/source-code-pro/refs/tags/2.042R-u/1.062R-i/1.026R-vf/WOFF2/VF/SourceCodeVF-Upright.ttf.woff2"
      - "https://raw.githubusercontent.com/adobe-fonts/source-code-pro/refs/tags/2.042R-u/1.062R-i/1.026R-vf/WOFF2/VF/SourceCodeVF-Italic.ttf.woff2"

  - family: "Fira Code"
    license:
      type: "SIL Open Font License 1.1"
      link: "https://github.com/tonsky/FiraCode/blob/6.2/LICENSE"
    files:
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/FiraCode/FiraCode-Bold.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/FiraCode/FiraCode-Light.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/FiraCode/FiraCode-Medium.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/FiraCode/FiraCode-Regular.woff2"
      - "https://raw.githubusercontent.com/pamburus/fonts/refs/heads/main/FiraCode/FiraCode-SemiBold.woff2"
