name: Update flake.lock

on:
  schedule:
    - cron: "30 16 * * FRI" # Every Friday at 16:30 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  update-lock:
    name: Update flake.lock
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - name: Create pull request for flake.lock update
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore(deps): update nix flake dependencies"
          branch: update-flake-lock
          title: "chore(deps): update flake.lock"
          body: "This pull request updates the flake.lock file with the latest flake inputs."
          author: "missionis[bot] <234988995+missionis[bot]@users.noreply.github.com>"
          committer: "missionis[bot] <234988995+missionis[bot]@users.noreply.github.com>"
          labels: |
            dependencies
            nix
          delete-branch: true

      - name: Enable auto-merge
        id: enable-auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: |
          gh pr merge --auto -ds ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ github.token }}
