name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Update flake.lock
        run: nix flake update

      - name: Create pull request for flake.lock update
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "build(nix): update flake.lock"
          branch: update-flake-lock
          title: "build(nix): update flake.lock"
          body: "This pull request updates the flake.lock file with the latest flake inputs."
          sign-commits: true
          token: ${{ secrets.PAT_TOKEN }}

      - name: Debug Logging
        run: |
          echo "Pull Request URL: ${{ steps.pr.outputs.pull-request-url }}"
          echo "Pull Request Number: ${{ steps.pr.outputs.pull-request-number }}"
