name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  BRANCH_NAME: update-flake-lock

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          git config user.signingkey $(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | cut -d'/' -f2)
          git config commit.gpgSign true
          git config user.name "GitHub Actions Bot"
          git config user.email "12778560+github-actions@users.noreply.github.com"
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo '#!/bin/sh' > ~/.gpg-no-tty.sh
          echo 'exec gpg --no-tty --batch --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" "$@"' >> ~/.gpg-no-tty.sh
          chmod +x ~/.gpg-no-tty.sh
          git config gpg.program "${HOME}/.gpg-no-tty.sh"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update flake.lock
        run: nix flake update

      - name: Check for changes
        id: check_changes
        run: |
          git add flake.lock
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
          git checkout -b $BRANCH_NAME
          git commit -m "build(nix): update flake.lock" -S
          git push origin $BRANCH_NAME
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create pull request with GitHub CLI
        run: |
          gh pr create --base main --head $BRANCH_NAME --title "build(nix): update flake.lock" --body "This pull request updates the flake.lock file with the latest flake inputs."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # - name: Create pull request for flake.lock update
      #   id: pr
      #   if: env.changes_detected == 'true'
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     base: ${{ github.head_ref }}
      #     branch: $BRANCH_NAME
      #     body: "This pull request updates the flake.lock file with the latest flake inputs."
      #     author: "github-actions[bot] <12778560+github-actions@users.noreply.github.com>"
      #     committer: "github-actions[bot] <12778560+github-actions@users.noreply.github.com>"
      #     token: ${{ secrets.PAT_TOKEN }}

      # - name: Debug Logging
      #   run: |
      #     echo "Pull Request URL: ${{ steps.pr.outputs.pull-request-url }}"
      #     echo "Pull Request Number: ${{ steps.pr.outputs.pull-request-number }}"
