name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          git config --global user.signingkey $(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | cut -d'/' -f2)
          git config --global commit.gpgSign true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Update flake.lock
        run: nix flake update

      - name: Create pull request for flake.lock update
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "build(nix): update flake.lock"
          branch: update-flake-lock
          title: "build(nix): update flake.lock"
          body: "This pull request updates the flake.lock file with the latest flake inputs."
